arquivo = open('palavras.txt', 'w')
arquivo.write('abacate\n')
arquivo.write('mamao\n')
arquivo.write('morango\n')
arquivo.write('laranja\n')
arquivo.write('limao\n')
arquivo.write('caju\n')
arquivo.write('goiaba\n')
arquivo.write('uva\n')
arquivo.write('tangerina\n')
arquivo.write('acerola\n')
arquivo.write('jabuticaba\n')
arquivo.write('carambola\n')
arquivo.write('cereja\n')
arquivo.write('framboesa\n')
arquivo.write('banana\n')
arquivo.close